name: Serzhan Cloud CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  ci:
    name: CI - Test Docker Build
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t serzhan-cloud-ci:${{ github.sha }} .

  deploy:
    name: CD - Deploy
    needs: ci
    runs-on: self-hosted

    steps:
      - name: Deploy with Ansible
        run: |
          cd /home/serzh/devops-lab/ansible
          ansible-playbook -i inventory.ini deploy.yml
