name: Deploy Serzhan Cloud

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Deploy with Ansible
        run: |
          cd /home/serzh/devops-lab/ansible
          ansible-playbook -i inventory.ini deploy.yml
